### ISSUE TITLE
Mod conflicts with

### ISSUE THREAD

**Issue by sahri-shr** [EvilDraggie/YingWorld#22]
It is somehow conflicting with a LWM's Deep Storage and Simple storage. There are problems with apparel list, it can't be shown properly
Also, why so many "{incert race here} already has short hash"?

**Comment by sahri-shr** [comment]
Yeah, it is not problem with other mods. Something is bugging in eltex apparel

**Comment by Avris** [comment]
You have Humanoid Alien Races enabled. We have a custom version built in for now, please disable it before reporting further bugs.
