### ISSUE TITLE
Caravans don't food

### ISSUE THREAD

**Issue by Avris** [EvilDraggie/YingWorld#28]
Caravans bring no food and fucking starve

**Comment by MrBriggs18** [comment]
Some genius has specifically assigned all yinglet pawnkinds ZERO nutrition in inventory. It's in our xml files, changing the number is as easy as going to pawnkind defs and altering the <invNutrition> value. Maybe move it over to the pawnkind bases so as not to rewrite for every god damn pawnkind on the list.

**Comment by MrBriggs18** [comment]
Fixed on dev branch
